// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjDXpYldXoP6iaPVC4r1i1F6upq9Tm270',
    appId: '1:270976940682:web:042f27d17494933bbecb73',
    messagingSenderId: '270976940682',
    projectId: 'laundrywala-f8fa6',
    authDomain: 'laundrywala-f8fa6.firebaseapp.com',
    storageBucket: 'laundrywala-f8fa6.appspot.com',
    measurementId: 'G-QWSWYT1HV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd6RExDgY5TVs5rOFJLix3bgYAJ7Fch0o',
    appId: '1:270976940682:android:05262d8c02088ca8becb73',
    messagingSenderId: '270976940682',
    projectId: 'laundrywala-f8fa6',
    storageBucket: 'laundrywala-f8fa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwnN16YuhwEWYTGXXRKVBt__dJb5W5pPc',
    appId: '1:270976940682:ios:96df894cc2d30be0becb73',
    messagingSenderId: '270976940682',
    projectId: 'laundrywala-f8fa6',
    storageBucket: 'laundrywala-f8fa6.appspot.com',
    iosBundleId: 'personal.laundryMama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwnN16YuhwEWYTGXXRKVBt__dJb5W5pPc',
    appId: '1:270976940682:ios:0a83c7f6e68cfecebecb73',
    messagingSenderId: '270976940682',
    projectId: 'laundrywala-f8fa6',
    storageBucket: 'laundrywala-f8fa6.appspot.com',
    iosBundleId: 'com.example.laundryMama.RunnerTests',
  );
}
